/*
* Advanced weighting script X
* Wraith - Game extraction tools
*/

global proc WraithMesh_6a757149_00_BindFunc()
{
   select -r WraithMesh_6a757149_00;
   select -add metal_shrapnel_a_02_l0;
   newSkinCluster "-toSelectedBones -mi 30 -omi true -dr 5.0 -rui false";   string $clu = findRelatedSkinCluster("WraithMesh_6a757149_00");

   skinPercent -tv metal_shrapnel_a_02_l0 1.0 $clu WraithMesh_6a757149_00.vtx[0:440];
}

global proc RunAdvancedScript()
{
   catch(WraithMesh_6a757149_00_BindFunc());
}

global proc NamespacePurge()
{
   string $allNodes[] = `ls`;
   for($node in $allNodes) {
      string $buffer[];
      tokenize $node ":" $buffer;
      string $newName = $buffer[size($buffer)-1];
       catchQuiet(`rename $node $newName`);
   }
}

print("Currently binding the current model, please wait...\n");
NamespacePurge();
RunAdvancedScript();
print("The model has been binded.\n");

